### ISSUE TITLE
Find the proper way to detect the a word in HTML elements

### ISSUE THREAD

**Issue by incleaf** [ChocolateFactory/dailydic-extension#1]
We should consider the performance to add events on elements.
These are some examples what I've found

- http://www.java2s.com/Code/JavaScript/jQuery/Tohighlightaclickedwordintheparagraph.htm
- http://jsfiddle.net/Vap7C/15/

**Comment by incleaf** [comment]
@yangroro @demarlik01

**Comment by incleaf** [comment]
http://jsfiddle.net/ohaf4ytL/

**Comment by incleaf** [comment]
https://developer.mozilla.org/ko/docs/Web/API/document/caretRangeFromPoint

**Comment by incleaf** [comment]
If you guys have no idea then I'll use this logic: http://jsfiddle.net/ohaf4ytL/
@yangroro @demarlik01

**Comment by yangroro** [comment]
@incleaf What is the pros and cons?

**Comment by incleaf** [comment]
Pros:
-  it works

Cons:
- I don't know is it right way

**Comment by yangroro** [comment]
How about Mozila's way. it is a more reliable

**Comment by demarlik01** [comment]
why am i included in this conversation..?

**Comment by incleaf** [comment]
That's not an official API so the name of method is all different in each browser.
I tried to figure out how does that API work a little bit, but I didn't know.
Anyway I'll look again that API then!

**Comment by incleaf** [comment]
@demarlik01 Because you will develop Android ^^

**Comment by yangroro** [comment]
@demarlik01 congratulation you included in this project

**Comment by yangroro** [comment]
@incleaf ok, it`s up to you

**Comment by demarlik01** [comment]
i'll unsubscribe this issue. bye!
